### ISSUE TITLE
get returning None

### ISSUE THREAD

**Issue by FroogalTheDragon** [tory1103/oh-my-pickledb#5]
**Bug Description:**
I wrote a very simple test program to learn to use this module.  I have two functions: `store()` and `retrieve()`

The store function works fine and is able to store and save the data passed to it to a .db file.

My retrieve function is very simple and straight forward.  This function is returning `None` instead of the value stored.  At this point I don't know if it's a me problem, or a bug.

I'm on Windows 11 (sadly), and I'm using python version 3.11.1

**my import:**
```
from my_pickledb import PickleDB as pickledb
```

**The store function:**
```
@classmethod
    def store(cls, key: str, img_as_text: str):
        db = pickledb('test.db')
        db.set(key, img_as_text)
        db.save.as_json()
```

**The retrieve function:**
```
@classmethod
    def retrieve(cls, key: str) -> str:
        db = pickledb('test.db')
        return db.get(key)
```

**Comment by tory1103** [comment]
PickleDB can't load saved database by default, try using LoadPickleDB instead.
Anyway, you can also add the loaded database to PickleDB with kwargs:
```python
def retrieve(cls, key: str) -> str:
    db = pickledb('test.db', **Load('test.db').as_json()')
    return db.get(key)
```
Hope this helps...
PD: When you're done, remember to close the issue.

**Comment by FroogalTheDragon** [comment]
> PickleDB can't load saved database by default, try using LoadPickleDB instead.
> Anyway, you can also add the loaded database to PickleDB with kwargs:
> ```python
> def retrieve(cls, key: str) -> str:
>     db = pickledb('test.db', **Load('test.db').as_json()')
>     return db.get(key)
> ```
> Hope this helps...
> PD: When you're done, remember to close the issue.

Will try this, thank you so much for the response 😊

Closing Issue.
